product_demo/product_demo/urls.py
from django.conf.urls import url
from django.contrib import admin
from product import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add/$', views.add, name='add'),
    url(r'^update/(?P<id>\d+)/$', views.update,name='update'),
    url(r'^delete/(?P<id>\d+)/$', views.delete,name='delete'),
    url(r'^list/$', views.list,name='list'),
    url(r'^add2/$', views.add2, name='add2'),

    url(r'^add3/$', views.add3, name='add3'),
    url(r'^update2/(?P<id>\d+)/$', views.update2,name='update2'),
    url(r'^update3/(?P<id>\d+)/$', views.update3,name='update3')
]

product_demo/product/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=10,verbose_name=u'分类名称')
    class Meta:
        verbose_name = u'产品分类'
        verbose_name_plural = verbose_name
    def __unicode__(self):
        return self.name

class Keyword(models.Model):
    name = models.CharField(max_length=10, verbose_name=u'关键词')
    class Meta:
        verbose_name = u'关键词'
        verbose_name_plural = verbose_name
    def __unicode__(self):
        return self.name

class Product(models.Model):
    spec_type=(
        ('1', '大号'),
        ('2', '中号'),
        ('3', '小号'),
    )
    name = models.CharField(max_length=10, verbose_name=u'产品名称')
    spec = models.CharField(max_length=1, choices=spec_type,verbose_name=u'产品型号')
    cate = models.ForeignKey(Category, verbose_name=u'产品类别')
    stock = models.IntegerField(default=100, verbose_name=u'库存数量')
    price = models.DecimalField(default=10.00, decimal_places=2, max_digits=8, verbose_name=u'产品价格')
    key = models.ManyToManyField(Keyword, verbose_name=u'关键词')
    #null=True, blank=True成对出现 null=True指数据库 blank=True指表单
    desc = models.TextField(null=True, blank=True, verbose_name=u'产品描述')
    class Meta:
        verbose_name = u'产品'
        verbose_name_plural = verbose_name
    def __unicode__(self):
        return self.name

product_demo/product/forms.py
#coding: utf-8
from django import forms
from product import models
class ProductForm(forms.ModelForm):
	class Meta:
		model = models.Product
		fields=('name','spec','cate','stock','price','key','desc')

class ProductForm2(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"请输入产品名称","class":"input-xlarge", }))
	spec=forms.ChoiceField(choices=models.Product.spec_type,widget=forms.Select(attrs={'class':'input-xlarge','name':'product_spec'}))
	cate = forms.ModelChoiceField(queryset=models.Category.objects.all(),widget=forms.Select(attrs={'class':'input-xlarge'}))
	stock = forms.IntegerField(widget=forms.TextInput(attrs={"placeholder":"请输入库存数量","name":"product_stock","class":"input-xlarge" }))
	price = forms.DecimalField(widget=forms.TextInput(attrs={"placeholder":"请输入产品价格","name":"product_price","class":"input-xlarge" }))
	key = forms.ModelMultipleChoiceField(queryset=models.Keyword.objects.all(),widget=forms.SelectMultiple(attrs={'class':'input-xlarge',}))
	desc = forms.CharField(widget=forms.Textarea(attrs={"name":"product_desc","rows":"2"}))
	#class Meta:
	#	model = models.Product
	#        fields=('name','spec','cate','stock','price','key','desc')
#	name=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"请输入产品名称","class":"input-xlarge", }))
#	spec=forms.ChoiceField(choices=models.Product.spec_type,widget=forms.Select(attrs={'class':'input-xlarge','name':'product_spec'}))
#	cate=forms.ModelChoiceField(queryset=models.Category.objects.all(),widget=forms.Select(attrs={'class':'input-xlarge','name':'product_cate'}))
#	stock=forms.IntegerField(widget=forms.TextInput(attrs={"placeholder":"请输入库存数量","name":"product_stock","class":"input-xlarge" }))
#	price=forms.DecimalField(widget=forms.TextInput(attrs={"placeholder":"请输入产品价格","name":"product_price","class":"input-xlarge" }))
#	key=forms.ModelMultipleChoiceField(queryset=models.Keyword.objects.all(),widget=forms.SelectMultiple(attrs={'class':'input-xlarge','name':'product_key'}))
#	desc=forms.CharField(widget=forms.Textarea(attrs={"name":"product_desc","rows":"2"}))
class QueryForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'请输入产品名','class':'input-xlarge'}))

product_demo/product/views.py
# coding: utf-8
from django.shortcuts import render,redirect
from product.models import Category,Keyword,Product
from django.core.paginator import Paginator
from product import forms
# Create your views here.

def add(request):
    if request.method == 'POST':
        post = request.POST
        product = Product.objects.create(
            name = post.get('product_name'),
            spec = post.get('product_spec'),
            cate_id = post.get('product_category'),
            stock = post.get('product_stock'),
            price = post.get('product_price'),
            desc = post.get('product_desc'))

        keylist = post.getlist('product_key')
        for key_id in keylist:
                product.key.add(key_id)
        return redirect('list')

    categorys = Category.objects.all()
    keywords = Keyword.objects.all()
    return render(request,'product/add.html',{'categorys':categorys,'keywords':keywords})

def update(request,id):

    if request.method == 'POST':
        product = Product.objects.get(pk=id)
        post = request.POST
        product.name = post.get('product_name')
        product.spec = post.get('product_spec')
        product.cate_id = post.get('product_category')
        product.stock = post.get('product_stock')
        product.price = post.get('product_price')
        product.desc = post.get('product_desc')
        keylist = post.getlist('product_key')
        for key_id in keylist:
            key = Keyword.objects.get(pk=key_id)
            if key not in product.key.all():
                product.key.add(key_id)
        for key in product.key.all():
            if str(key.id) not in keylist:
                product.key.remove(key)
        product.save()

        return redirect('list')
    product = Product.objects.get(pk=id)
    categorys = Category.objects.all()
    keywords = Keyword.objects.all()
    return render(request, 'product/update.html', locals())

def delete(request,id):
    product = Product.objects.get(pk=id)
    product.delete()
    return redirect('list')

def list(request):
    products = Product.objects.order_by('-id')
    paginator = Paginator(products,3)
    try:
        page = int(request.GET.get('page'))
        products = paginator.page(page)
    except:
        products = paginator.page(1)
    return render(request,'product/list.html',locals())
def add2(request):
	if request.method == 'POST':
		product_form = forms.ProductForm(request.POST)
		product_form.save()
		return redirect('list')
		
	product_form = forms.ProductForm()
	return render(request, 'product/add2.html', locals())
def update2(request, id):
	product = Product.objects.get(pk=id)
	if request.method == 'POST':
		product_form = forms.ProductForm(request.POST, instance=product)
		product_form.save()
		return redirect('list')
	product_form = forms.ProductForm()
	return render(request, 'product/update2.html', locals())
	

product_demo/templates/product/add.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品添加</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'add' %}>
    {% csrf_token %}
    <fieldset>
      <div id="legend" class="">
        <legend class="">添加产品</legend>
      </div>
    

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品名</label>
          <div class="controls">
            <input type="text" placeholder="请输入产品名称" class="input-xlarge" name = "product_name">
            <p class="help-block"></p>
          </div>
        </div>

    

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品型号</label>
          <div class="controls">
            <select class="input-xlarge" name = "product_spec">
      <option value="1">大号</option>
      <option value="2">中号</option>
      <option value="3">小号</option></select>
          </div>

        </div>

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品类别</label>
          <div class="controls">
            <select class="input-xlarge" name = "product_category">
                {% for category in categorys %}
                    <option value={{ category.id }}>{{ category.name }}</option>
                {% endfor %}

            </select>
          </div>

        </div>

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">库存数量</label>
          <div class="controls">
            <input type="text" placeholder="请输入库存数量" class="input-xlarge" name = "product_stock">
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品价格</label>
          <div class="controls">
            <input type="text" placeholder="请输入产品价格" class="input-xlarge" name = "product_price">
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Select Multiple -->
          <label class="control-label">产品关键词</label>
          <div class="controls">
            <select class="input-xlarge" multiple="multiple" name = "product_key">
                {% for key in keywords %}
                    <option value={{ key.id }}>{{ key.name }}</option>
                {% endfor %}
            </select>

          </div>
        </div>
        <div class="control-group">

          <!-- Textarea -->
          <label class="control-label">产品描述</label>
          <div class="controls">
            <div class="textarea">
                  <textarea type="" class="" name = "product_desc"> </textarea>
            </div>
          </div>
        </div>

    <div class="control-group">
          <label class="control-label"></label>

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">添加</button>
          </div>
        </div>

    </fieldset>
  </form>


</body>
</html>

product_demo/templates/product/add2.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品添加</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'add2' %}>
    {% csrf_token %}
    {{ product_form.as_p }}
    <input type="submit" value="send">
 </form>


</body>
</html>

product_demo/templates/product/add3.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品添加</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'add3' %}>
    {% csrf_token %}
    <fieldset>
      <div id="legend" class="">
        <legend class="">添加产品</legend>
      </div>
    

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品名</label>
          <div class="controls">
	  {{product_form.name}}
        </div>

    
<p>
    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品型号</label>
          <div class="controls">
	  {{product_form.spec}}
                  </div>

        </div>

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品类别</label>
          <div class="controls">
	  {{product_form.cate}}
                  </div>

        </div>

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">库存数量</label>
          <div class="controls">
	  {{product_form.stock}}
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品价格</label>
          <div class="controls">
	  {{product_form.price}}
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Select Multiple -->
          <label class="control-label">产品关键词</label>
          <div class="controls">
	  {{product_form.key}}
            
          </div>
        </div>
        <div class="control-group">

          <!-- Textarea -->
          <label class="control-label">产品描述</label>
          <div class="controls">
            <div class="textarea">
	    {{product_form.desc}}
            </div>
          </div>
        </div>

    <div class="control-group">
          <label class="control-label"></label>

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">添加</button>
          </div>
        </div>

    </fieldset>
  </form>


</body>
</html>

product_demo/templates/product/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="UTF-8">
   <title>产品列表</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<form method="post" action="{% url 'list' %}">
{% csrf_token %}
{{query_form}}<input type="submit" value="search">
</form>
<div id="legend" class="">
  <legend class="">产品列表&nbsp;&nbsp;<a href="{% url 'add' %}"><small>添加</small></a></legend>
</div>
<table class="table table-hover">
   <thead>
      <tr>
         <th>产品名称</th>
         <th>产品型号</th>
         <th>产品类别</th>
          <th>库存数量</th>
         <th>产品价格</th>
          <th>操作</th>

      </tr>
   </thead>
   <tbody>
   {% for product in products %}
      <tr>
         <td>{{ product.name }}</td>
         <td>{{ product.get_spec_display }}</td>
         <td>{{ product.cate }}</td>
        <td>{{ product.stock }}</td>
         <td>{{ product.price }}</td>
        <td><a href="{% url 'update3' product.id%}">修改</a>|
            <a href="{% url 'delete' product.id%}">删除</a></td>

      </tr>
   {% endfor %}
   </tbody>
</table>
<ul class="pager">
    {{ products.number }}/{{ products.paginator.num_pages }}
  {% if products.has_previous %}
  <li><a href="?page={{ products.previous_page_number }}">上一页</a></li>
  {% endif %}
    {% if products.has_next %}
  <li><a href="?page={{ products.next_page_number }}">下一页</a></li>
    {% endif %}
</ul>
</body>
</html>

product_demo/templates/product/update.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品修改</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'update' product.id%}>
    {% csrf_token %}
    <fieldset>
      <div id="legend" class="">
        <legend class="">修改产品</legend>
      </div>
    

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品名</label>
          <div class="controls">
            <input type="text" value="{{ product.name }}" class="input-xlarge" name = "product_name">
            <p class="help-block"></p>
          </div>
        </div>

    

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品型号</label>
          <div class="controls">
            <select class="input-xlarge" name = "product_spec">
      <option value="1"{% ifequal product.spec '1' %}selected{% endifequal %}>大号</option>
      <option value="2"{% ifequal product.spec '2' %}selected{% endifequal %}>中号</option>
      <option value="3"{% ifequal product.spec '3' %}selected{% endifequal %}>小号</option></select>
          </div>

        </div>

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品类别</label>
          <div class="controls">
            <select class="input-xlarge" name = "product_category">
                {% for category in categorys %}
                    <option value={{ category.id }} {% ifequal product.cate category %}selected{% endifequal %}>{{ category.name }}</option>
                {% endfor %}

            </select>
          </div>

        </div>

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">库存数量</label>
          <div class="controls">
            <input type="text" value="{{ product.stock }}" class="input-xlarge" name = "product_stock">
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品价格</label>
          <div class="controls">
            <input type="text" value="{{ product.price }}" class="input-xlarge" name = "product_price">
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Select Multiple -->
          <label class="control-label">产品关键词</label>
          <div class="controls">
            <select class="input-xlarge" multiple="multiple" name = "product_key">
                {% for key in keywords %}
                    <option value={{ key.id }} {% if key in product.key.all %}selected{% endif %}>{{ key.name }}</option>
                {% endfor %}
            </select>

          </div>
        </div>
        <div class="control-group">

          <!-- Textarea -->
          <label class="control-label">产品描述</label>
          <div class="controls">
            <div class="textarea">
                  <textarea type="" class="" name = "product_desc">{{ product.desc }} </textarea>
            </div>
          </div>
        </div>

    <div class="control-group">
          <label class="control-label"></label>

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">修改</button>
          </div>
        </div>

    </fieldset>
  </form>


</body>
</html>

product_demo/templates/product/update2.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品修改</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'update2' product.id%}>
    {% csrf_token %}
    {{ product_form.as_p}}
    <input type="submit" value="send">
 </form>


</body>
</html>

product_demo/templates/product/update3.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>产品添加</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

  
  <form class="form-horizontal" method="post" action={% url 'update3' product.id %}>
    {% csrf_token %}
    <fieldset>
      <div id="legend" class="">
        <legend class="">添加产品</legend>
      </div>
    

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品名</label>
          <div class="controls">
	  {{product_form.name}}
        </div>

    
<p>
    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品型号</label>
          <div class="controls">
	  {{product_form.spec}}
                  </div>

        </div>

    <div class="control-group">

          <!-- Select Basic -->
          <label class="control-label">产品类别</label>
          <div class="controls">
	  {{product_form.cate}}
                  </div>

        </div>

    <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">库存数量</label>
          <div class="controls">
	  {{product_form.stock}}
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Text input-->
          <label class="control-label" for="input01">产品价格</label>
          <div class="controls">
	  {{product_form.price}}
            <p class="help-block"></p>
          </div>
        </div>
        <div class="control-group">

          <!-- Select Multiple -->
          <label class="control-label">产品关键词</label>
          <div class="controls">
	  {{product_form.key}}
            
          </div>
        </div>
        <div class="control-group">

          <!-- Textarea -->
          <label class="control-label">产品描述</label>
          <div class="controls">
            <div class="textarea">
	    {{product_form.desc}}
            </div>
          </div>
        </div>

    <div class="control-group">
          <label class="control-label"></label>

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">添加</button>
          </div>
        </div>

    </fieldset>
  </form>


</body>
</html>

product_demo/templates/test.html
{{desc}}